-- 状态仪表盘内置插件入口。
--
-- 本文件只保留空入口。状态页的 stats/weather 函数由 LynAI 宿主在
-- `plugin.func` 中直接实现，不依赖 Lua handler。
-- 状态页外观文件（status.html/status.css）是 manifest 中声明的可编辑
-- overlay 文件，可通过插件工坊或全局插件文件工具修改，并随时恢复默认。
